In [205]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix

In [206]:
data = pd.read_csv('advertising.csv')

In [207]:
print(data.shape)

(1000, 10)

In [221]:
print(data.isnull().sum())

Daily Time Spent on Site    0
Age                         0
Area Income                 0
Daily Internet Usage        0
Male                        0
                           ..
zero                        0
Hour                        0
Day                         0
Month                       0
DayOfWeek                   0
Length: 355, dtype: int64

In [208]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   str
 5   City                      1000 non-null   str
 6   Male                      1000 non-null   int64
 7   Country                   1000 non-null   str
 8   Timestamp                 1000 non-null   str
 9   click                     1000 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 151.1 KB
None

In [209]:
le=LabelEncoder()

In [210]:
data["city"]=le.fit_transform(data["City"])
data["country"]=le.fit_transform(data["Country"])
data

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,click,city,country
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0,961,215
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0,903,147
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0,111,184
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0,939,103
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0,805,96
...,...,...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,Fundamental modular algorithm,Duffystad,1,Lebanon,2016-02-11 21:49:00,1,126,116
996,51.30,45,67782.17,134.42,Grass-roots cohesive monitoring,New Darlene,1,Bosnia and Herzegovina,2016-04-22 02:07:01,1,488,26
997,51.63,51,42415.72,120.37,Expanded intangible solution,South Jessica,1,Mongolia,2016-02-01 17:24:57,1,798,140
998,55.55,19,41920.79,187.95,Proactive bandwidth-monitored policy,West Steven,0,Guatemala,2016-03-24 02:35:54,0,935,85
999,45.01,26,29875.80,178.35,Virtual 5thgeneration emulation,Ronniemouth,0,Brazil,2016-06-03 21:43:21,1,744,28

In [211]:
data = data.drop(columns=['City', 'Country'])
data

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,Male,Timestamp,click,city,country
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,0,2016-03-27 00:53:11,0,961,215
1,80.23,31,68441.85,193.77,Monitored national standardization,1,2016-04-04 01:39:02,0,903,147
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,0,2016-03-13 20:35:42,0,111,184
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,1,2016-01-10 02:31:19,0,939,103
4,68.37,35,73889.99,225.58,Robust logistical utilization,0,2016-06-03 03:36:18,0,805,96
...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,Fundamental modular algorithm,1,2016-02-11 21:49:00,1,126,116
996,51.30,45,67782.17,134.42,Grass-roots cohesive monitoring,1,2016-04-22 02:07:01,1,488,26
997,51.63,51,42415.72,120.37,Expanded intangible solution,1,2016-02-01 17:24:57,1,798,140
998,55.55,19,41920.79,187.95,Proactive bandwidth-monitored policy,0,2016-03-24 02:35:54,0,935,85
999,45.01,26,29875.80,178.35,Virtual 5thgeneration emulation,0,2016-06-03 21:43:21,1,744,28

In [212]:
tfidf = TfidfVectorizer()
text_features = tfidf.fit_transform(data['Ad Topic Line'])
text_df = pd.DataFrame(
    text_features.toarray(),
    columns=tfidf.get_feature_names_out()
)

data = data.drop(columns=['Ad Topic Line'])
data = pd.concat([data, text_df], axis=1)
data

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,Timestamp,click,city,country,24,...,visionary,volatile,warehouse,web,website,well,wide,workforce,worthy,zero
0,68.95,35,61833.90,256.09,0,2016-03-27 00:53:11,0,961,215,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,80.23,31,68441.85,193.77,1,2016-04-04 01:39:02,0,903,147,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,69.47,26,59785.94,236.50,0,2016-03-13 20:35:42,0,111,184,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,74.15,29,54806.18,245.89,1,2016-01-10 02:31:19,0,939,103,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,68.37,35,73889.99,225.58,0,2016-06-03 03:36:18,0,805,96,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,1,2016-02-11 21:49:00,1,126,116,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
996,51.30,45,67782.17,134.42,1,2016-04-22 02:07:01,1,488,26,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,51.63,51,42415.72,120.37,1,2016-02-01 17:24:57,1,798,140,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,55.55,19,41920.79,187.95,0,2016-03-24 02:35:54,0,935,85,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,45.01,26,29875.80,178.35,0,2016-06-03 21:43:21,1,744,28,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [213]:
data['timestamp'] = pd.to_datetime(data['Timestamp'], errors='coerce')

data['Hour'] = data['timestamp'].dt.hour
data['Day'] = data['timestamp'].dt.day
data['Month'] = data['timestamp'].dt.month
data['DayOfWeek'] = data['timestamp'].dt.dayofweek
data=data.drop(columns=["Timestamp"])
data=data.drop(columns=["timestamp"])
data

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,click,city,country,24,24hour,...,website,well,wide,workforce,worthy,zero,Hour,Day,Month,DayOfWeek
0,68.95,35,61833.90,256.09,0,0,961,215,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,27,3,6
1,80.23,31,68441.85,193.77,1,0,903,147,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,4,4,0
2,69.47,26,59785.94,236.50,0,0,111,184,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20,13,3,6
3,74.15,29,54806.18,245.89,1,0,939,103,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2,10,1,6
4,68.37,35,73889.99,225.58,0,0,805,96,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3,3,6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,1,1,126,116,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,21,11,2,3
996,51.30,45,67782.17,134.42,1,1,488,26,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2,22,4,4
997,51.63,51,42415.72,120.37,1,1,798,140,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,17,1,2,0
998,55.55,19,41920.79,187.95,0,0,935,85,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2,24,3,3
999,45.01,26,29875.80,178.35,0,1,744,28,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,21,3,6,4

In [214]:
X = data.drop(columns=['click'])  # Features (excluding 'credit')
y = data['click']  # Target variable ('credit')

In [215]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [216]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [217]:
y_pred = model.predict(X_test)

In [218]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Test accuracy: ",accuracy)

Test accuracy:  0.97

In [219]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[142   4]
 [  5 149]]

In [220]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       146
           1       0.97      0.97      0.97       154

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300